### ISSUE TITLE
Package downloads M-NIST digit rec. DB at every iteration

### ISSUE THREAD

**Issue by anjos** [bioidiap/bob.db.mnist#2]
This package is downloading the M-NIST database from the respective URL (LeCun's site) at every iteration. The reason is that it has no way to know where it previously downloaded a copy (because it is using a temporary directory to do so).

It would be more useful if the database was downloaded to a known directory.

I'd propose this database provided a "create" action that would allow it to be downloaded and installed within the package.

**Comment by tiagofrepereira2012** [comment]
In think we should reactivate this one.
I will implement a download action. It is easy and painless

**Comment by tiagofrepereira2012** [comment]
Done with 5f9cd1f
